name: "Build and deploy to server"

on:
  push:
    # Chúng ta sẽ chạy khi chúng ta release một version mới
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tags docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/200lab-nextjs # Change this to your docker image name
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Deploy server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            docker pull ${{ steps.meta.outputs.tags }}
            docker rm -f 200lab-next &>/dev/null
            docker run -it -d --name 200lab-next -p 3000:3000 ${{ steps.meta.outputs.tags }}
#      - name: Deploy
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.SSH_KEY }}
#
#          script: |
##           Pull image về lại server
#            docker pull ${{ steps.meta.outputs.tags }}
##           Xóa container cũ nếu có
#            docker rm -f 200lab-next &>/dev/null
##           Chạy container mới
#            docker run -it -d --name 200lab-next -p 3000:3000 ${{ steps.meta.outputs.tags }}